matrix:
  include:
    - language: node_js
      node_js: "12.18.3"
      before_script:
        - cd coding-mbti
        - yarn global add create-react-app
        - yarn install
      cache:
        directories:
          - node_modules
      script:
        - yarn test -- --coverage
      before_deploy:
        - yarn build
        - zip -r coding-mbti-webservice build/* ../appspec.yml ../execute-deploy.sh ../execute-before-install.sh
        - mkdir -p deploy
        - mv coding-mbti-webservice.zip deploy/coding-mbti-webservice.zip
      deploy:
        - provider: s3                      # frontend dev
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          bucket: coding-mbti-1-deploy
          local_dir: deploy
          region: us-east-1
          skip_cleanup: true                
          wait-until-deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: dev
        - provider: codedeploy
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          bucket: coding-mbti-1-deploy
          key: coding-mbti-webservice.zip
          bundle_type: zip
          application: coding-mbti-1-deploy
          deployment_group: coding-mbti-1-deploy-group
          region: us-east-1
          wait-until-deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: dev
        - provider: s3                      # frontend master
          access_key_id: $AWS_ACCESS_KEY_2
          secret_access_key: $AWS_SECRET_KEY_2
          bucket: coding-mbti-1-deploy      # bucket name in S3
          local_dir: deploy
          region: us-east-1
          skip_cleanup: true                # prevent travis from removing built files 
          wait-until-deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: master
        - provider: codedeploy
          access_key_id: $AWS_ACCESS_KEY_2
          secret_access_key: $AWS_SECRET_KEY_2
          bucket: coding-mbti-1-deploy
          key: coding-mbti-webservice.zip
          bundle_type: zip
          application: coding-mbti-1-deploy
          deployment_group: coding-mbti-1-deploy-group
          region: us-east-1
          wait-until-deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: master
      after_success:
        - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn run coveralls

notifications:
  slack: coding-mbti:mpufjN3PylzT8q8HgpXJDdun
