matrix:
  include:
    - language: node_js
      node_js:
        - "13.12.0"
      before_script:
        - cd coding-mbti
        - yarn global add create-react-app
        - yarn install
      cache:
        directories:
          - node_modules
      script:
        - yarn test -- --coverage
      before_deploy:
        - yarn build
        - cp ../aws-codedeploy-scripts/frontend/* ./build
        - zip -r coding-mbti-webservice build/*
        - mkdir -p deploy
        - mv coding-mbti-webservice.zip deploy/coding-mbti-webservice.zip
      deploy:
        - provider: s3                      # frontend dev s3
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          bucket: coding-mbti-1-deploy
          local_dir: deploy
          region: us-east-1
          skip_cleanup: true                
          wait_until_deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: dev
        - provider: codedeploy              # frontend dev codedeploy
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          bucket: coding-mbti-1-deploy
          key: coding-mbti-webservice.zip
          bundle_type: zip
          application: coding-mbti-1-deploy
          deployment_group: coding-mbti-1-deploy-group
          region: us-east-1
          wait_until_deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: dev
        - provider: s3                      # frontend master s3
          access_key_id: $AWS_ACCESS_KEY_2
          secret_access_key: $AWS_SECRET_KEY_2
          bucket: coding-mbti-2-deploy      
          local_dir: deploy
          region: us-east-1
          skip_cleanup: true                
          wait_until_deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: master
        - provider: codedeploy              # frontend master codedeploy
          access_key_id: $AWS_ACCESS_KEY_2
          secret_access_key: $AWS_SECRET_KEY_2
          bucket: coding-mbti-2-deploy
          key: coding-mbti-webservice.zip
          bundle_type: zip
          application: coding-mbti-2-deploy
          deployment_group: coding-mbti-2-deploy-group
          region: us-east-1
          wait_until_deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: master
        - provider: s3                      # backend dev s3
          access_key_id: $AWS_ACCESS_KEY_3
          secret_access_key: $AWS_SECRET_KEY_3
          bucket: coding-mbti-3-deploy
          local_dir: deploy
          region: us-east-1
          skip_cleanup: true                
          wait_until_deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: dev
        - provider: codedeploy              # backend dev codedeploy
          access_key_id: $AWS_ACCESS_KEY_3
          secret_access_key: $AWS_SECRET_KEY_3
          bucket: coding-mbti-3-deploy
          key: coding-mbti-webservice.zip
          bundle_type: zip
          application: coding-mbti-3-deploy
          deployment_group: coding-mbti-3-deploy-group
          region: us-east-1
          wait_until_deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: dev
        - provider: s3                      # backend master s3
          access_key_id: $AWS_ACCESS_KEY_4
          secret_access_key: $AWS_SECRET_KEY_4
          bucket: coding-mbti-4-deploy      
          local_dir: deploy
          region: us-east-1
          skip_cleanup: true                
          wait_until_deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: master
        - provider: codedeploy              # backend master codedeploy
          access_key_id: $AWS_ACCESS_KEY_4
          secret_access_key: $AWS_SECRET_KEY_4
          bucket: coding-mbti-4-deploy
          key: coding-mbti-webservice.zip
          bundle_type: zip
          application: coding-mbti-4-deploy
          deployment_group: coding-mbti-4-deploy-group
          region: us-east-1
          wait_until_deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: master
      after_success:
        - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn run coveralls
    - language: python
      python:
        - "3.7"
      before_script:
        - cd coding-mbti/backend
        - pip install -r requirements.txt
        - pip install coverage
        - pip install coveralls
      script:
        - coverage run -m unittest
      before_deploy:
        - mkdir ../backend-build
        - cp ./* ../backend-build
        - cp ../../aws-codedeploy-scripts/backend/* ../backend-build
        - zip -r coding-mbti-backend ../backend-build/*
        - mkdir -p backend-deploy
        - mv coding-mbti-backend.zip backend-deploy/coding-mbti-backend.zip
      deploy:
        - provider: s3                      # backend dev s3
          access_key_id: $AWS_ACCESS_KEY_3
          secret_access_key: $AWS_SECRET_KEY_3
          bucket: coding-mbti-3-deploy
          local_dir: backend-deploy
          region: us-east-1
          skip_cleanup: true                
          wait_until_deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: dev
        - provider: codedeploy              # backend dev codedeploy
          access_key_id: $AWS_ACCESS_KEY_3
          secret_access_key: $AWS_SECRET_KEY_3
          bucket: coding-mbti-3-deploy
          key: coding-mbti-backend.zip
          bundle_type: zip
          application: coding-mbti-3-deploy
          deployment_group: coding-mbti-3-deploy-group
          region: us-east-1
          wait_until_deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: dev
        - provider: s3                      # backend master s3
          access_key_id: $AWS_ACCESS_KEY_4
          secret_access_key: $AWS_SECRET_KEY_4
          bucket: coding-mbti-4-deploy      
          local_dir: backend-deploy
          region: us-east-1
          skip_cleanup: true                
          wait_until_deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: master
        - provider: codedeploy              # backend master codedeploy
          access_key_id: $AWS_ACCESS_KEY_4
          secret_access_key: $AWS_SECRET_KEY_4
          bucket: coding-mbti-4-deploy
          key: coding-mbti-backend.zip
          bundle_type: zip
          application: coding-mbti-4-deploy
          deployment_group: coding-mbti-4-deploy-group
          region: us-east-1
          wait_until_deployed: true
          on:
            repo: swsnu/swpp2020-team16
            branch: master
      after_success:
        - coveralls

notifications:
  slack: coding-mbti:mpufjN3PylzT8q8HgpXJDdun
